Initial commit of ring fall
temple2018/Galaxia pull request #31
Opened 2018-08-09 05:48 UTC by ColinBarnes

My inspiration for this pattern is the movement a ring or hula hoop makes when its dropped on the ground, circling and teetering as it rolls around on its edge before landing flat.

My friend is going to help build the temple this year, and he knows I like graphics programming so he pointed me at this project and recommended I try making something.

2018-08-10 17:24 UTC, deleted requested changes
This pattern looks awesome!

We're asking that all animations speeds be able to be set super slow; the temple is a sacred place. Would you mind adjusting the lower bounds of your speed parameters?

2018-08-10 17:24 UTC, deleted commented on src/main/java/org/templegalaxia/patterns/cbarnes/RingFall.java
> +      new BoundedParameter("Ang-vel", 7500, 10000, 250); // Angle change speed
Please call `setDescription()` to add text descriptions to these parameters, that we can see from the LX UI.

Also, can you make the lower limit of the speed parameters slower? Like 20-30 second rotations at the lower bounds?

2018-08-10 20:36 UTC, ColinBarnes commented
Thank you! I'll make those changes later today.

2018-08-13 20:20 UTC, deleted approved these changes

2018-08-13 20:21 UTC, merged